spring.datasource.url=jdbc:duckdb:
spring.datasource.driver-class-name=org.duckdb.DuckDBDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLDialect
spring.jpa.hibernate.ddl-auto=update

trino.url=jdbc:trino://example.com:443
trino.user=admin

async.executor.core-pool-size=5
async.executor.max-pool-size=10
async.executor.queue-capacity=25
